version: '2.3'
services:
  app:
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  restify:
    image: open-apparel-registry-restify-api
    build:
      context: ./src/restify
      dockerfile: Dockerfile
    volumes:
      - ./src/restify/config:/usr/local/src/config
      - ./src/restify/src:/usr/local/src/src
      - ./src/restify/yarn.lock:/usr/local/src/yarn.lock
      - ./src/restify/package.json:/usr/local/src/package.json
      - $HOME/.aws:/root/.aws:ro
    env_file: .env.backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=2000
      - PORT=8000
    ports:
      - 8000:8000
    working_dir: /usr/local/src
    depends_on:
        mongo:
            condition: service_healthy
        elasticsearch:
            condition: service_healthy
    entrypoint: yarn
    command: run dev

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.4
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    env_file: .env.backend
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test: curl --silent --fail localhost:9200/_cluster/health || exit 1
      interval: 3s
      timeout: 3s
      retries: 12

  mongo:
    image: mongo:4.1.6-xenial
    volumes:
      - mongo_data:/data/db
    env_file: .env.backend
    healthcheck:
      test: echo 'db.stats().ok' | mongo --quiet
      interval: 3s
      timeout: 3s
      retries: 12

volumes:
  elasticsearch_data:
    driver: local
  mongo_data:
    driver: local
